# Use the same version of Flink as your jobmanager and taskmanager
FROM flink:1.14.5

# Copy the JAR file into the container
COPY target/WeatherDataProcessor-1.0-jar-with-dependencies.jar /opt/flink/usrlib/WeatherDataProcessor-1.4.jar
